services:
  eureka-service:
    build: ./eureka
    networks:
      - tenant-infrastructure
    ports:
      - "8761:8761"
  gateway-service:
    build: ./gateway
    networks:
      - tenant-infrastructure
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
  movies-service:
    build: ./movies
    networks:
      - tenant-infrastructure
    depends_on:
      - eureka-service
      - gateway-service
      - database
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - tenant-infrastructure

networks:
  tenant-infrastructure: